import type { Metadata } from 'next';
import Header from '@/components/Header/Header';
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <div className='flex min-h-screen flex-col items-center justify-between mx-auto max-w-[1920px]'>
          <Header/>
          {children}
        </div>   
      </body>
    </html>
  )
}
